### ISSUE TITLE
Can't subdivide TOSCA shapes

### ISSUE THREAD

**Issue by antonognik** [HTDerekLiu/neuralSubdiv#10]
I'm trying to subdivide the TOSCA shapes ([Non-rigid world](https://tosca.cs.technion.ac.il/book/resources_data.html)) that were used in the paper for comparing the different methods.

For all shapes, except 3, I either get the error 'mesh has boundary' or 'edge non-manifold' in the SSP_decimation.m script.

**Comment by HTDerekLiu** [comment]
ohh we have a newer version of this that supports mesh with boundaries here https://github.com/HTDerekLiu/surface_multigrid_code/tree/main/09_random_subdiv_remesh.

You could try this out to see whether it works :)

**Comment by antonognik** [comment]
Thanks a lot for the reply :)

I tried the newer version and it works for meshes with boundaries. However, it doesn't work when the input mesh is not manifold. 

What I'm trying to do is make some modifications in NeuralSubdivision and compare it with the rest of the results as seen in Table 2 of the paper: 
![image](https://github.com/HTDerekLiu/neuralSubdiv/assets/46850364/643c1f51-7c6c-4c0c-9e96-bcfc0e7dc29a)

I'm using the [Non-rigid world](https://tosca.cs.technion.ac.il/book/resources_data.html) meshes. Were these the ones used in the original paper? 

Currently, from the centaur category only centaur1 and centaur2 are being decimated. The rest of the category are not manifold.

**Comment by HTDerekLiu** [comment]
Hmm I can't recall where I found a cleaned manifold version of the dataset. But I was able to locate the meshes I used in the original paper in my hard drive, see https://www.dropbox.com/scl/fi/rhpaq4y2vzthqxel9bh28/subdiv_results.zip?rlkey=n4eq5ti4tukdoy4mxgenj3wq1&dl=0.

Hope this helps!

**Comment by antonognik** [comment]
This certainly helps!

The only thing that I'm missing are the subdivided meshes used for the training of the network. (So I can train the modified one).

If you could find those I'd be really grateful

**Comment by HTDerekLiu** [comment]
This should be the centaur shapes I trained on
https://www.dropbox.com/scl/fi/2g700mmwg5gtp6q5kbpjz/centaur_training_shapes.zip?rlkey=t5t3cpoz60bfdf0p0dg09fs81&dl=0

**Comment by antonognik** [comment]
Hey :)

Thanks a lot for the help so far!

I have one final question. 

Do you have the other categories' (David, horse) shapes you trained the network with? (like the ones above)

**Comment by therateful** [comment]
hello, could you please share a Tosca dataset with me? The official website seems to have canceled the resource download

**Comment by HTDerekLiu** [comment]
Hi, you can download TOSCA from Vova's website http://www.vovakim.com/projects/CorrsBlended/doc_data.html

**Comment by therateful** [comment]
thank you very much
