### ISSUE TITLE
Genreate My Training  Data too Slow

### ISSUE THREAD

**Issue by MaybeOjbk** [HTDerekLiu/neuralSubdiv#3]
hi,  I use Matlab code to generate a single mesh data, but I find it takes around 5 minutes.  (40k vertexes and  80k faces)  So ，is there any faster method to generate the training set?

**Comment by HTDerekLiu** [comment]
Not yet, we are still working on a C++ implementation, we will update this function when it is ready! If interested, you could also quickly implement one by combining the existing implementation of qslim and lscm in , for instance, libigl
- qslim: https://github.com/libigl/libigl/blob/master/include/igl/qslim.h
- lscm: https://github.com/libigl/libigl/blob/master/include/igl/lscm.h
