### ISSUE TITLE
Quantitative evaluation

### ISSUE THREAD

**Issue by 1999kevin** [HTDerekLiu/neuralSubdiv#5]
Hi, do you provide any code to evaluate the output mesh quantitively? I can see in your paper that you use two popular metrics, Hausdorff distance H, and mean surface distance M computed via metro [Cignoni et al. 1998] to present the results compared woth loop subdivision and modified butterfly subdivision. How can I find the implementation of these two metrics?

**Comment by HTDerekLiu** [comment]
I used the implementation from this website https://sourceforge.net/projects/vcg/files/. They released the executable so it should be easy to use.

**Comment by 1999kevin** [comment]
> I used the implementation from this website https://sourceforge.net/projects/vcg/files/. They released the executable so it should be easy to use.

Thank you very much for your reply. I will try it later.
