### ISSUE TITLE
Issue for mesh data

### ISSUE THREAD

**Issue by 1999kevin** [HTDerekLiu/neuralSubdiv#6]
I am very interested in this work and I want to re-perform some experiments. Have you finished the faster version of genTrainData.m? And is it possible for this program to be preformed with less criteria, such as on non-manifold meshes in Shapenet? Could you please provide those original mesh data that you use to perform the stylized subdivision experiments, shown in appended image? 

![1642996831(1)](https://user-images.githubusercontent.com/37931674/150719993-430cf48d-c8ed-4ffb-a06a-cacba0285f6d.png)

**Comment by HTDerekLiu** [comment]
Hello,

> Have you finished the faster version of genTrainData.m?

I haven't cooked up the fast version of this exact function. But we have fast version of all the components in here https://github.com/HTDerekLiu/surface_multigrid_code/tree/main/01_single_SSP. This computes the bijective map, so you just need to add subdivided point queries on top of this. 

> And is it possible for this program to be preformed with less criteria?

Unfortunately, it belongs to future work. But I believe it is for sure possible :) 

> stylized subdivision experiments

The meshes are here: https://www.dropbox.com/home/Projects/20_SIG_neuralSubdiv/LoD_Tex/figureCode/datadriven

Hope you enjoy it!

**Comment by 1999kevin** [comment]
@HTDerekLiu  
Thank you for your kindly response! For the url(https://www.dropbox.com/home/Projects/20_SIG_neuralSubdiv/LoD_Tex/figureCode/datadriven), I think it belongs to a personal Dropbox account, so except you, we cannot visit this url and download any files from it. To transfer files through Dropbox, you need to create a Dropbox Transfer, select the files in your Dropbox and paste a link here. An example Dropbox Transfer link should be: https://www.dropbox.com/t/eEF4aCh6EV0jcuoP . 

Thank you again and I would be very appreciated if you can transfer the files to me!

**Comment by HTDerekLiu** [comment]
Oops this one should work: https://www.dropbox.com/sh/1wu9mw7qb0nszsw/AAC1GXBZqoJFF-UTiioMSiUDa?dl=0

**Comment by 1999kevin** [comment]
Got it! Thank you very much
