### ISSUE TITLE
How to set nV_variance/nV_average in genTrainData_slow.m

### ISSUE THREAD

**Issue by nagisa-eevee** [HTDerekLiu/neuralSubdiv#7]
Should I change the parameters `nV_variance` and `nV_average` depending on the number of vertices/faces in the input mesh?
I find these two parameters used in `SSP_decimation(Vin,Fin,nVc, 'QEM', 0.1,0.4,true)`, where `nVc = nV_average + round(nV_variance * (rand() - 0.5))`.

**Comment by HTDerekLiu** [comment]
Sorry for the late reply. `nV_average` controls the number of (average) vertices on the coarse mesh and `nV_variance` controls the magnitude of perturbation . For example, if `nV_average = 500` and `nV_variance = 10`, then your output vertices should lie within the range of 495~505 vertices. 

In case you want a faster version, we also provide a faster version here https://github.com/HTDerekLiu/surface_multigrid_code/tree/main/09_random_subdiv_remesh.

**Comment by nagisa-eevee** [comment]
Thank you for your reply. I've tried the cpp version and it's much faster. Thanks for your code.
