### ISSUE TITLE
Issue for original mesh data

### ISSUE THREAD

**Issue by zhuzhiwei99** [HTDerekLiu/neuralSubdiv#8]
I am very interested in this work and I want to re-perform some experiments.  Could you please provide the **original mesh data** that you used in your paper? Thanks very much!

**Comment by HTDerekLiu** [comment]
Most of our mesh data are from the "10k surface meshes" obtained here https://github.com/Yixin-Hu/TetWild and https://www.cs.cmu.edu/~kmcrane/Projects/ModelRepository/. If you have any specific ones in mind, let us know.

**Comment by zhuzhiwei99** [comment]
Thank you for your reply!  I will try to download files from that two links. 

One more question，have you simplified or modified these files when using them as Ground Truth in your paper? I'm trying to replicate your experiment, but I'm worried that the way I did it might not be the way you did.  So, could you please pack the GT files of these models ( **[elephant, bunny, catcus, fish, horse, rockerArm]**)  and  the Gt files of **models appeared in the following pictures** and then paste a download link in this issue.

Thank you again and I would be very appreciated if you can transfer the files to me!
![image](https://user-images.githubusercontent.com/45233826/225835196-24f282dc-25c3-417e-b2bf-317065ca2c17.png)
![image](https://user-images.githubusercontent.com/45233826/225835241-197f90b3-298f-47a6-b1b1-1009f7f09e83.png)
![image](https://user-images.githubusercontent.com/45233826/225835290-5977aefb-6582-4380-bfb4-affe992e6bb8.png)
![image](https://user-images.githubusercontent.com/45233826/225835464-2c53bd0d-7414-4e12-aaca-fbf742387709.png)

**Comment by HTDerekLiu** [comment]
I just dumped the models here https://github.com/HTDerekLiu/neuralSubdiv/tree/master/data_meshes/objs_original, except the egg one which requires permission from the creator. 

Enjoy them!

**Comment by zhuzhiwei99** [comment]
Thanks a million!
